### ISSUE TITLE
Custom colors with webpacker

### ISSUE THREAD

**Issue by ngouy** [blocknotes/activeadmin_blaze_theme#11]
From the read me :

using webpacker
>If you are using Webpacker:

> Add the component to the package.json: yarn add blocknotes/activeadmin_blaze_theme
Add at the end of your Active Admin javascript pack (app/javascript/packs/active_admin.js):
require('activeadmin_blaze_theme');

custom colors : 

> To change colors add to your Active Admin styles (before activeadmin_blaze_theme/theme import):

How can we combine both to make variables works ?

If I try to require the js file after I import my scss file where my styles customization variables are, it just doesn't works

```js
import "../my_css_style_sheet"
require('activeadmin_blaze_theme')
```

(the other way around doesn't works either)

**Comment by blocknotes** [comment]
Hey @ngouy.
Good point 😄 

You can try in this way:
- update _app/javascript/stylesheets/active_admin.scss_ with:
```scss
// these first 2 lines should already be present
@import "~@activeadmin/activeadmin/src/scss/mixins";
@import "~@activeadmin/activeadmin/src/scss/base";

$color-brand: #c02;
// ... and the other vars ...
@import "~activeadmin_blaze_theme/app/assets/stylesheets/activeadmin_blaze_theme/theme";
```
- remove `require('activeadmin_blaze_theme')` from the js.

**Comment by ngouy** [comment]
Will do

Thank you for providing this gem and also help users. 💪
