### ISSUE TITLE
has_many buttons don't have a blaze style

### ISSUE THREAD

**Issue by stefsava** [blocknotes/activeadmin_blaze_theme#17]
![image test](https://user-images.githubusercontent.com/19606/120883877-08728080-c5e0-11eb-81d0-03719c052727.png)

**Comment by blocknotes** [comment]
It should be fixed by this commit: https://github.com/blocknotes/activeadmin_blaze_theme/commit/3a8750f592a07d53e2de0b7d45fb5f0880fd74ac

Also consider to move the associations inside the `inputs` block.

**Comment by stefsava** [comment]
Perfect, it works well.
Thank you.
Beautiful work.
