### ISSUE TITLE
Filter Selection Showing in Sidebar

### ISSUE THREAD

**Issue by lauraannwilliams** [blocknotes/activeadmin_blaze_theme#2]
On my Mac Chrome, the filter is showing the selected item, instead of hiding it as in the screenshots. Is there an extra step to get this working?

<img width="260" alt="screen shot 2018-01-04 at 1 15 55 pm" src="https://user-images.githubusercontent.com/7003598/34584646-706a538c-f151-11e7-9b8b-4ef34c1819a3.png">

Thank you very much

**Comment by blocknotes** [comment]
Hi @lauraannwilliams 
It seems a problem with a CSS style not overridden.
What version of ActiveAdmin? The latest activeadmin_blaze_theme?
If you try with another browser the problem is the same?

**Comment by lauraannwilliams** [comment]
The problem mysteriously went away. I am assuming I had another style conflicting!
