### ISSUE TITLE
Consider removing SassC from runtime dependencies

### ISSUE THREAD

**Issue by Fs00** [blocknotes/activeadmin_blaze_theme#23]
SassC is not needed for those who are using this gem with Webpacker, since Webpack already takes care of SCSS transpilation.
[ActiveAdmin stopped depending on SassC](https://github.com/activeadmin/activeadmin/pull/6584) when they started to support Webpacker and I think this gem should do the same, considering also that SassC takes quite some time to install.

**Comment by blocknotes** [comment]
Yeah, I agree - the choice of the SASS/SCSS processing library should rely on the application.
I'll work on this.
